language: node_js
version: 1.0
node_js:
  - '16'
sudo: required
dist: trusty
addons:
  chrome: stable
cache:
  directories:
    - $HOME/.npm
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install codecov -g
  - npm ci --ignore-scripts
script:
  # run build script specified in package.json
  - npm run ci
after_success:
  - codecov
before_deploy:
  - cd dist/elements
after_deploy:
  - cd ../../
deploy:
  - provider: npm
    edge: true
    email: tomas.trajan@gmail.com
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true
  - provider: pages
    name: tomastrajan
    email: tomas.trajan@gmail.com
    local_dir: dist/elements-demo
    skip_cleanup: true
    github_token: $GH_TOKEN
